import { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; // Global CSS that applies to the entire app
import Header from "./components/Header"; // Import the Header component
import Footer from "./components/Footer"; // Import the Footer component
import { CartProvider } from './components/CartContext'; // Adjust path accordingly

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Wrap the entire app with CartProvider */}
        <CartProvider>
          {/* Include the Header component */}
          <Header />

          {/* Main Content Area */}
          <main className="global-layout"> {/* Add the 'global-layout' class here */}
            {children}
          </main>

          {/* Include the Footer component */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
